COMPARTMENT = "<COMPARTMENT ID FROM GEN AI>" 
CONFIG_FILE = "~/.oci/config"
CONFIG_PROFILE = "DEFAULT"
# Service endpoint
ENDPOINT = "<INFERENCE GENERATIVE AI ENDPOINT>"
LLM_MODEL_ID = "GENERATIVE AI MODEL ID>"
DB_USER = "<HW DB USER>"
DB_PASSWORD = "<HW DB PASSWORD>"
DB_HOST = "<HW PRIVATE IP>"
DB_PORT = 3306
DB_SCHEMA = "<WORDPRESS SCHEMA>"

COHERE_API_KEY = "COHERE API KEY"

REGION = "us_chicago-1"

DEDICATED_RERANK_ENDPOINT = "<DEDICATED GENAI CLUSTER ENDPOINT>"

DEBUG = False
DEBUG_PAUSE = False
